//
// Created by Εκλεκτός εν Χριστώ on 7/15/24.
//

/*
 * data captured by reference is allowed to be modified inside the lambda by default
 *
 * compiler generates the captured references as data members in the functor class, the members will also
 * be a reference
 *
 * only the used references inside the lambda are going to be generated by the compiler as data members
 */

#include <iostream>

int main()
{
    int a{ 98 };
    int b{ 191 };

    auto lambda1{ [&](){

        // references are allowed to be modified inside lambda
        // compiler will generate a and b as reference data members and not a and b
        // this allows modification
        std::cout << ++a << '\n';
        std::cout << b << '\n';
    } };

    lambda1();

    return 0;
}