//
// Created by Εκλεκτός εν Χριστώ on 3/7/24.
//

/*
 * defaulted constructor - if we want the default constructor to be generated by the compiler and not
 * ourselves, we can use = default; after the empty parameter list of constructor, in this way we can use both
 * default and parameterized constructors
 */

#include <iostream>

const double PI{ 3.14 };

class Cylinder
{
public:
    // default constructor - explicitly marked
    Cylinder() = default;

    Cylinder(double r_param, double h_param)
    {
        base_radius = r_param;
        height = h_param;
    }

    double volume()
    {
        return PI * base_radius * base_radius * height;
    }

private:
    double base_radius{};
    double height{};
};

int main()
{
    Cylinder c1;
    std::cout << c1.volume() << '\n';

    return 0;
}